services:
  samba:
    container_name: docker_smb
    tty: true
    hostname: Docker
    image: ghcr.io/brandonkowalski/romm-smb-opl:latest
    volumes:
      - type: bind
        source: { REPLACE_ME }
        target: /mnt/ps2smb
    restart: unless-stopped
    ports:
      - "445:445/tcp"